name: build

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]
  release:
    types: [ published ]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "11.1.2"

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Install Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Install Ghidra ${{matrix.version}}
        uses: antoniovazquezblanco/setup-ghidra@v2.0.3
        with:
          version: ${{matrix.version}}

      - name: Build plugin via gradle
        run: gradle -PZIP_NAME_PREFIX=ghidra_${{matrix.version}}

      - name: Rename artifact ZIP
        run: mv dist/*_${{matrix.version}}_*.zip dist/ghidra_${{matrix.version}}_${{github.event.repository.name}}.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ghidra_${{matrix.version}}_${{github.event.repository.name}}
          path: dist/*${{github.event.repository.name}}.zip

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'release' && github.event.action == 'published'

    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        
      - name: Download binaries
        uses: actions/download-artifact@v4

      - name: Upload release ZIP
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: gh release upload ${{github.event.release.tag_name}} *${{github.event.repository.name}}/*.zip
